### ISSUE TITLE
Feature request: Support variables syntax

### ISSUE THREAD

**Issue by pdgendt** [tree-sitter-grammars/tree-sitter-kconfig#4]
It would be nice to be able to support something like the following:

```
RANGE_MIN := 1
RANGE_MAX := 3

config FOO
        int "foo"
        range $(RANGE_MIN) $(RANGE_MAX)
```

The example above is mentioned [here](https://www.kernel.org/doc/html/next/kbuild/kconfig-macro-language.html#caveats).

Currently view with `InspectTree`:
<img width="556" alt="image" src="https://github.com/amaanq/tree-sitter-kconfig/assets/3170234/643631c8-c681-4809-ab50-717dc5bfe1dd">

**Comment by amaanq** [comment]
thanks, I forgot about that. fixed on master

**Comment by pdgendt** [comment]
Hey @amaanq, a follow-up remark :)

Commas are allowed in variables, as they are delimiters for functions, so the following is valid:

```
comma := ,
$(shell, echo hello$(comma) world)
```
The example above is mentioned [here](https://docs.kernel.org/kbuild/kconfig-macro-language.html#make-vs-kconfig).

`InspectTree`:
<img width="523" alt="image" src="https://github.com/amaanq/tree-sitter-kconfig/assets/3170234/d9abc5e7-8c4c-4462-9105-fbb90e166a2c">

**Comment by amaanq** [comment]
thanks, fixed

**Comment by pdgendt** [comment]
> thanks, fixed

I need to learn the grammar syntax to create PRs 😅 does this support multiple commas in variables?

Thanks for the fast responses!

**Comment by amaanq** [comment]
hm not sure what you mean, if you have a link to the docs on some parts that aren't implemented here I can flesh it out more

**Comment by pdgendt** [comment]
> hm not sure what you mean, if you have a link to the docs on some parts that aren't implemented here I can flesh it out more

An example that, I think, is allowed:

```
commas := this,text,has,commas
$(shell, echo hello$(commas) world)
```

Is this supported?

**Comment by amaanq** [comment]
that's getting a bit confusing - what determines the end of a variable, it can't be just a newline, so..? (maybe 2?)

**Comment by pdgendt** [comment]
> that's getting a bit confusing - what determines the end of a variable, it can't be just a newline, so..? (maybe 2?)

I think it does go to a newline, the `Kconfig` variables work the same as `Makefile` variables, see:
https://ftp.gnu.org/old-gnu/Manuals/make-3.79.1/html_chapter/make_6.html#SEC64

**Comment by pdgendt** [comment]
Additionally I think `+=` concatenates whatever is behind it, similar to the assignment.

**Comment by pdgendt** [comment]
The variable assignment for `make` has an explicit newline: 

https://github.com/alemuller/tree-sitter-make/blob/a4b9187417d6be349ee5fd4b6e77b4172c6827dd/grammar.js#L232-L240

EDIT: there is probably an issue there as well as it could have a comment at the end instead of a newline..
