### ISSUE TITLE
bug: help can be empty 

### ISSUE THREAD

**Issue by Freed-Wu** [tree-sitter-grammars/tree-sitter-kconfig#9]
### Did you check existing issues?

- [X] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser
- [X] I have searched the existing issues

### Tree-Sitter CLI Version, if relevant (output of `tree-sitter --version`)

0.22.3

### Describe the bug

```kconfig

mainmenu "PetaLinux System Configuration"
config SUBSYSTEM_TYPE_LINUX
        bool
        default y
        select SYSTEM_ZYNQMP

config SYSTEM_ZYNQMP
        bool "ZYNQMP Configuration"
        help
          ZYNQMP Configuration for petalinux project.
          All these config options will be in /home/wzy/Desktop/soc/project-spec/configs/config


config SUBSYSTEM_VARIANT_ZYNQMPEV
        bool
        default y
        help

# Copyright (C) 2021-2022, Xilinx, Inc.  All rights reserved.
# Copyright (C) 2022, Advanced Micro Devices, Inc.  All rights reserved.
#
# SPDX-License-Identifier: MIT
#
menu "Linux Components Selection"
# ...
endmenu
```

help can be empty.

### Steps To Reproduce/Bad Parse Tree

![screen-2024-05-20-16-28-14](https://github.com/tree-sitter-grammars/tree-sitter-kconfig/assets/32936898/44505e61-e5bd-4e8d-a3a4-d1dd04b014ca)

```schema
(mainmenu) ; [2:1 - 41]
 name: (prompt) ; [2:10 - 41]
(config) ; [3:1 - 8:0]
 name: (symbol) ; [3:8 - 27]
 (type_definition) ; [4:9 - 5:0]
 (default_value) ; [5:9 - 6:0]
  (symbol) ; [5:17 - 17]
 (reverse_dependencies) ; [6:9 - 8:0]
  (symbol) ; [6:16 - 28]
(config) ; [8:1 - 15:0]
 name: (symbol) ; [8:8 - 20]
 (type_definition) ; [9:9 - 10:0]
  (prompt) ; [9:14 - 35]
 (help_text) ; [10:9 - 15:0]
  (text) ; [11:11 - 15:0]
(config) ; [15:1 - 1594:0]
 name: (symbol) ; [15:8 - 33]
 (type_definition) ; [16:9 - 17:0]
 (default_value) ; [17:9 - 18:0]
  (symbol) ; [17:17 - 17]
 (help_text) ; [18:9 - 1594:0]
  (text) ; [20:1 - 1594:0]
```

### Expected Behavior/Parse Tree

20:1 - 1594:0 shouldn't be text.

**Comment by amaanq** [comment]
I don't think it's allowed to be empty, running `./scripts/kconfig/conf` on your input gives me this:

`Kconfig:19: 'SUBSYSTEM_VARIANT_ZYNQMPEV' defined with blank help text`

It seems like it's disallowed by their parser - https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/scripts/kconfig/parser.y#n408
